blank_issues_enabled: true
contact_links:
  - name: 🏥F&Q讨论专区（F&Q Discussion Forum）
    url: https://github.com/freeCB/balala/discussions/categories/q-a-%E7%AD%94%E7%96%91%E5%8C%BA
    about: 前往F&Q讨论专区进行交流（Head over to the F&Q Discussion Forum to connect）🏥
